"""
Export utilities - Excel and PDF for ShipPipe results.
"""
import io
import pandas as pd
from fpdf import FPDF


def to_excel(pipe_result: dict, pump_result: dict, bom_df: pd.DataFrame,
             system: str, vessel_name: str) -> bytes:
    """Export results to Excel workbook (3 sheets)."""
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        # Sheet 1 - Pipe Sizing
        pipe_df = pd.DataFrame([pipe_result]).T.reset_index()
        pipe_df.columns = ["Parameter", "Value"]
        pipe_df.to_excel(writer, sheet_name="Pipe Sizing", index=False)

        # Sheet 2 - Pump Specification
        pump_df = pd.DataFrame([pump_result]).T.reset_index()
        pump_df.columns = ["Parameter", "Value"]
        pump_df.to_excel(writer, sheet_name="Pump Specification", index=False)

        # Sheet 3 - BOM
        bom_df.to_excel(writer, sheet_name="Bill of Materials")

        # Sheet 4 - Cover
        cover = pd.DataFrame({
            "Field": ["Vessel / Project", "System", "Generated By", "Tool"],
            "Value": [vessel_name, system, "ShipPipe", "pipe.sujikumar.com"],
        })
        cover.to_excel(writer, sheet_name="Cover", index=False)

    return output.getvalue()



def _safe(text):
    """Remove non-latin-1 chars for fpdf compatibility."""
    return str(text).encode('latin-1', errors='replace').decode('latin-1')

def to_pdf(pipe_result: dict, pump_result: dict, bom_df: pd.DataFrame,
           system: str, vessel_name: str) -> bytes:
    """Export results to PDF spec sheet."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(0, 100, 160)
    pdf.cell(0, 10, "ShipPipe - Marine Piping System Designer", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"System: {system}   |   Vessel / Project: {vessel_name}   |   pipe.sujikumar.com", ln=True, align="C")
    pdf.ln(4)
    pdf.set_draw_color(0, 180, 220)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    def section_header(title):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 100, 160)
        pdf.cell(0, 8, title, ln=True)
        pdf.set_text_color(30, 30, 30)
        pdf.set_font("Helvetica", "", 9)

    def kv_row(k, v, shade=False):
        if shade:
            pdf.set_fill_color(240, 248, 255)
            pdf.cell(90, 6, _safe(k), border=1, fill=True)
            pdf.cell(90, 6, _safe(v), border=1, fill=True, ln=True)
        else:
            pdf.cell(90, 6, _safe(k), border=1)
            pdf.cell(90, 6, _safe(v), border=1, ln=True)

    # Pipe Sizing
    section_header("1. Pipe Sizing Results")
    for i, (k, v) in enumerate(pipe_result.items()):
        kv_row(k.replace("_", " ").title(), v, shade=(i % 2 == 0))
    pdf.ln(4)

    # Pump Spec
    section_header("2. Pump Specification")
    for i, (k, v) in enumerate(pump_result.items()):
        kv_row(k.replace("_", " ").title(), v, shade=(i % 2 == 0))
    pdf.ln(4)

    # BOM
    section_header("3. Bill of Materials")
    col_widths = [80, 15, 15, 70]
    headers = ["Item", "Qty", "Unit", "Specification"]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(0, 100, 160)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(headers, col_widths):
        pdf.cell(w, 7, h, border=1, fill=True)
    pdf.ln()
    pdf.set_text_color(30, 30, 30)
    pdf.set_font("Helvetica", "", 8)
    for i, row in bom_df.iterrows():
        shade = (int(str(i)) % 2 == 0)
        if shade:
            pdf.set_fill_color(245, 250, 255)
        vals = [_safe(row["Item"]), _safe(row["Qty"]), _safe(row["Unit"]),
                _safe(str(row["Specification / Notes"])[:55])]
        for val, w in zip(vals, col_widths):
            pdf.cell(w, 6, val, border=1, fill=shade)
        pdf.ln()

    # Footer
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "Generated by ShipPipe - Marine Piping System Designer | Suji Kumar C | pipe.sujikumar.com", align="C")

    return bytes(pdf.output())
